version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building with Maven..."
      - mvn -B clean install

artifacts:
    files:
        - '**/*'
    base-directory: $CODEBUILD_SRC_DIR
    discard-paths: no