AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance for development"
Resources:
  AppServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-039a8ebebdd2a1def"